### ISSUE TITLE
converting nic's link_down integers to bool for qemu

### ISSUE THREAD

**Issue by sophiexiaoyan** [Telmate/proxmox-api-go#103]
I use the terraform-provider-proxmox. When I run terraform import, I got this error: 
Error: network.1.link_down: '' expected type 'bool', got unconvertible type 'int'
I see there is a pull request resolve a similar error for firewall: https://github.com/Telmate/proxmox-api-go/pull/97
Can we do the same fix for link_down?

**Comment by gryrxn** [comment]
Same issue here. Agree with @sophiexiaoyan, I think a #97 equivalent fix is all that would be needed.

**Comment by Support-Green-IT-Solutions** [comment]
Hi, I just make this fix for proxmox_vm_qemu before seeing this issue. On my test environment, it works great.
You can found it here : https://github.com/GreenItSolutions/proxmox-api-go/tree/fix-link_down-type-bool.
