### ISSUE TITLE
config file prompted even for targets that dont require config

### ISSUE THREAD

**Issue by thorntonmc** [Telmate/proxmox-api-go#168]
#164 created the following issue for me. 

Part of my workflow involves getting a list of all VMs. This does not normally require a config file, however since `GetConfig` is always called now, it expects some sort of config to be directed in from stdin (which hangs indefinitely if nothing is directed) .

Is this intended? If not, I can create the PR to resolve this issue -- I just wanted to make sure if this was the intended workflow or not.

**Comment by Tinyblargon** [comment]
Thanks for reporting this.

This behavior was not intended when i made the change.
Currently the --file flag and os.stdin are only intended to supply a config when a item gets set/created/updated.

**Comment by thorntonmc** [comment]
Thanks @Tinyblargon - I'll throw up a PR and @ you on it.

**Comment by mleone87** [comment]
closing it if it's working as expected now
