### ISSUE TITLE
[request] allow for self signed certificates

### ISSUE THREAD

**Issue by shantanugadgil** [Telmate/proxmox-api-go#2]
When I try this with my Proxmox Server to start/stop a VM, I get the error msg:
`x509: certificate is valid for ...`

_I suspect it would be because of the self-signed certificate._

My command:
```
./proxmox-api-go -debug start 105
```

This works with another server which has a valid certificate.

Regards,
Shantanu

**Comment by ggongaware** [comment]
This is finally available using "-insecure" :
```
 ./proxmox-api-go -insecure start 105
```
