### ISSUE TITLE
/access/ticket": x509: 

### ISSUE THREAD

**Issue by zhang192073** [Telmate/proxmox-api-go#217]
pveum role add TerraformProv -privs "VM.Allocate VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Monitor VM.Audit VM.PowerMgmt Datastore.AllocateSpace Datastore.Audit"
pveum user add terraform-prov@pve
pveum aclmod / -user terraform-prov@pve -role TerraformProv
pveum user token add terraform-prov@pve terraform-token --privsep=0
┌──────────────┬──────────────────────────────────────┐
│ key          │ value                                │
╞══════════════╪══════════════════════════════════════╡
│ full-tokenid │ terraform-prov@pve!terraform-token   │
├──────────────┼──────────────────────────────────────┤
│ info         │ {"privsep":"0"}                      │
├──────────────┼──────────────────────────────────────┤
│ value        │ 477e8ccc-838f-404a-927f-342864e971fe │
└──────────────┴──────────────────────────────────────┘

PM_API_URL=https://192.168.200.211:8006/api2/json
PM_PASS=477e8ccc-838f-404a-927f-342864e971fe
PM_USER=terraform-prov@pve

└─# ./proxmox-api-go -debug start 103
2022/11/26 06:27:43 Post "https://192.168.200.211:8006/api2/json/access/ticket": x509: certificate signed by unknown authority

**Comment by mleone87** [comment]
use` -insecure` flag
