### ISSUE TITLE
Support PCI passthrough to vm

### ISSUE THREAD

**Issue by michaelze** [Telmate/proxmox-api-go#223]
We are trying to configure VMs with infiniband devices being passed through from the host.

I found Telmate/terraform-provider-proxmox#299, which states, that passing through PCI devices is currently not supported and that work has to be done within this repo to make it happen.

I'd love to help make this happen as it would simplify our setup and prevent some tedious manual work when provisioning new VMs for our k8s cluster.

Any advice on where to start? What to consider?

**Comment by dronenb** [comment]
I was looking into adding this for use with the Terraform provider, but correct me if I'm wrong, but wasn't this already added in [this commit](https://github.com/Telmate/proxmox-api-go/commit/c79df29a0a353aae22afa983b24447985cb31615)?

**Comment by Tinyblargon** [comment]
This was re-implemented by #376 now we have full PCI support with raw and mapped IDs.
