### ISSUE TITLE
Improving test coverage of parts of the API used by Terraform

### ISSUE THREAD

**Issue by rf152** [Telmate/proxmox-api-go#246]
I figured it's worth having an issue to capture the progress of the tests written

## General Access
- [x] User/Password authentication
- [x] User/Api Token authentication

## Qemu VM
- [x] Create
- [x] Read
- [x] Update
- [x] Delete
- [x] Cloud-init

## LXC Container
- [x] Create
- [x] Read
- [x] Update
- [x] Delete

## Pool
- [x] Create
- [x] Read
- [x] Update
- [x] Delete

**Comment by rf152** [comment]
PR #245 Contains a fair number of tests.

I've also got a branch that I'm currently writing that adds the ability to interact with API tokens (although not their permissions at the moment), which opens up the ability to test the login with API tokens.

As to the LXC containers I've hit a bit of a wall because there is currently no method for importing / downloading templates via the go api, so that needs writing first. I'm hesitant to write the function before the layout has been fully planned (currently being discussed in #210), so I'm at a bit of an impasse.

One option may be to write a quick and dirty hack to get a template downloaded so that I can write tests for the LXC stuff, which should then get us most of the coverage for testing the parts that are used by the Terraform API

**Comment by mleone87** [comment]
nice! feel free to notify me when it's ready to merge!

**Comment by rf152** [comment]
@mleone87 that's as much as I can do at the moment, until we have a method for importing LXC containers, so I think it makes sense to merge #245, and I'll do another pull request when I've written a hack for importing LXC containers

**Comment by rf152** [comment]
Cloud-init now sorted in #258

Think this puts us in a good position to start refactoring the whole application
