### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by Tinyblargon** [Telmate/proxmox-api-go#269]
Hi @mleone87, would it be an idea if i started working on a style guide for the code base?

I have noticed that depending on which part of the code was used for reference, the code style completely changes.

**Comment by mleone87** [comment]
hello @Tinyblargon, absolutely yes!

**Comment by dandyrow** [comment]
This could help greatly with any efforts related to issue #210!

**Comment by Tinyblargon** [comment]
Closing this issue as the style guide has been created and merged.
