### ISSUE TITLE
How do you compile this

### ISSUE THREAD

**Issue by sunilsankar** [Telmate/proxmox-api-go#3]
Hi I have no knowledge on go . When I tried following the steps mentioned I get

[sunil@gitlab-runner ~]$ go build -o proxmox-api-go
/usr/local/go/src/proxmox-api-go/main.go:6:2: cannot find package "github.com/Telmate/proxmox-api-go/proxmox" in any of:
        /usr/local/go/src/vendor/github.com/Telmate/proxmox-api-go/proxmox (vendor tree)
        /usr/local/go/src/github.com/Telmate/proxmox-api-go/proxmox (from $GOROOT)
        /home/sunil/projects/src/src/github.com/Telmate/proxmox-api-go/proxmox (from $GOPATH)
[sunil@gitlab-runner ~]$

Can you please help me solve this

**Comment by sunilsankar** [comment]
Please close this issue I think have solved this issue

**Comment by raarts** [comment]
How did you solve it?
