### ISSUE TITLE
Add cicustom to cloud-init supported options.

### ISSUE THREAD

**Issue by lukasmrtvy** [Telmate/proxmox-api-go#31]
`cicustom` is crucial cloud-init option to support. For example: if cloud-init ready template has no openssh-server package.

**Comment by ggongaware** [comment]
Good Idea, not sure how I missed that field before

**Comment by lukasmrtvy** [comment]
@ggongaware You should also keep an eye on https://bugzilla.proxmox.com/show_bug.cgi?id=2208 :) 

1. upload snippet (cloud-init-custom.yml) via API
2. Use `cicustom: "meta=mystorage:snippets/cloud-init-custom.yml" `

**Comment by zimmertr** [comment]
Is this working for anyone else? No matter what I am never able to connect to my VMs using the specified SSH key after provisioning.. And since I don't have access to logs it's very difficult to troubleshoot.
