### ISSUE TITLE
Issue creating QEMU VMs with Pool scoped users or API tokens

### ISSUE THREAD

**Issue by mpywell** [Telmate/proxmox-api-go#366]
After the Pool config refactor QEMU VMs are created against `/vms` then moved into `/pool/%s` if a Pool is configured. 

Pools are often used in hosted or enterprise Proxmox environments to scope user or API Token access , to avoid seeing/modifying the VMs of other users or teams. 

VMs cannot be created without giving access to `/vms` after #335 .

Configured Pools need to be passed into API requests to `/nodes/%s/qemu` to resolve the issue.

**Comment by Tinyblargon** [comment]
@mpywell thanks you for reporting this.
