### ISSUE TITLE
Interface conversion error in NewConfigQemuFromApi

### ISSUE THREAD

**Issue by johnpc35** [Telmate/proxmox-api-go#82]
One of the changes in #78 is causing an error when `NewConfigQemuFromApi` is called:

```
panic: interface conversion: interface {} is float64, not bool
goroutine 52 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc000443528, 0xc0005f6640, 0x0, 0x0, 0x0)
	/home/johnpc/go/src/github.com/Telmate/proxmox-api-go/proxmox/config_qemu.go:457 +0x3235
```

This is used by the `getConfig` command as well as the Terrform Proxmox Provider when cloning a template or VM.

Additionally, this flag needs to be defaulted to `true` where possible, otherwise it keeps the default value of `false` which is then passed to Proxmox when creating or updating a VM.

**Comment by romantomjak** [comment]
Awesome, thanks for spotting (and fixing) the problem @johnpc35! 🚀

**Comment by johnpc35** [comment]
Tested from the Terraform Provider and it seems to be working fine now.
